version: "3.3"

services:
  my-arts-backend:
    container_name: my-arts
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: "info"