INSERT INTO product_tags (id, product_id, title)
VALUES (1, 1, 'abstract art'),
       (2, 1, 'abstract expressionism'),
       (3, 1, 'large painting'),
       (4, 1, 'modern abstract painting'),
       (5, 1, 'abstract wall art'),
       (6, 1, 'minimal abstract painting'),
       (7, 1, 'organic abstract'),
       (8, 1, 'industrial abstract'),
       (9, 1, 'acrylic abstract painting'),
       (10, 1, 'expressive abstract art'),
       (11, 1, 'xl abstract art'),
       (12, 1, 'white abstract painting'),
       (13, 1, 'textured abstract art'),
       (14, 1, 'brushstrokes painting')
